KeisukeYamashita/commitlint-rs

.github/dependabot.yaml
Update PR title's `type` because I would like to use `bump` instead of the default `build`.
=> feat(.github): update pr title type

.editorconfig, examples/.commitlint.yaml, web/src/content/docs/config/configuration.md, web/src/content/docs/config/default.md, web/src/content/docs/rules/body-empty.md, web/src/content/docs/rules/body-max-length.md, web/src/content/docs/rules/description-empty.md, web/src/content/docs/rules/description-format.md, web/src/content/docs/rules/description-max-length.md, web/src/content/docs/rules/scope-empty.md, web/src/content/docs/rules/scope-format.md, web/src/content/docs/rules/scope-max-length.md, web/src/content/docs/rules/scope.md, web/src/content/docs/rules/subject-empty.md, web/src/content/docs/rules/type-empty.md, web/src/content/docs/rules/type-format.md, web/src/content/docs/rules/type-max-length.md, web/src/content/docs/rules/type.md
To format the YAML with `2` spaces.
=> feat(other): add editor config

.github/workflows/lint.yaml
To make review easy!
I forgot to run the Clippy on PR run so I have introduced the `sksat/action-clippy@main` GItHub Action action.
=> feat(.github): add clippy lint reviewdog action

web/src/content/docs/index.mdx
Fixes #175 
We are using the [Starlight](https://starlight.astro.build/) so we can't have `index.astro`. 
Therefore, I had to navigate to the first rule.
=> fix(web): broken `Read the rules` button

.pre-commit-hooks.yaml, Cargo.lock, src/args.rs
I wanted to use this together with [pre-commit](https://pre-commit.com/) but noticed that support for `--edit` was missing, so I went ahead and added at least the default using `./.git/COMMIT_EDITMSG`.
Also added a `.pre-commit-hooks.yaml` so that the repo can be used together with `pre-commit`.  Nothing fancy here...
And, thanks for this! Much better than the node commitlint solution for rust projects :)
=> feat(cli): add support for --edit and pre-commit

web/src/content/docs/setup/install.md
Fixes: https://github.com/KeisukeYamashita/commitlint-rs/issues/206
`commitlint` is totally a different cargo package. The correct one is:
https://github.com/KeisukeYamashita/commitlint-rs/blob/4bc1f521f514b58902ea18ada3157ecc182eaa8a/Cargo.toml#L2
=> fix(web): install target cargo name `commitlint-rs` from `commitlint`

.gitignore, Cargo.lock, src/git.rs, src/main.rs, src/rule/scope.rs, src/rule/type.rs
commit message is "", it's panic。
commit message invalid type ,it's panic.  like this “xx”。
=> fix(cli): panic on empty commit or empty type

src/config.rs
The logic for searching for the config file was incorrectly pushing paths to the PathBuf without popping, causing it to look for the wrong file paths.
I found that it was not detecting the yaml configuration files. I investigated and found this.
=> fix(cli): loading configuration files

web/src/content/docs/setup/debug.md
To let users easy to debug their configuration before putting this tool into product and make them confident to make updates.
=> feat(web): add how to debug page

web/src/content/docs/setup/debug.md
Because I sometimes what to know if the config file is loaded correctly or not.
=> feat(web): add debug instructure for config load

src/rule/description_max_length.rs
Because if the description is empty, the error emits saying that the description is too long.
=> fix(cli): ignore error on empty description

src/main.rs
No need to use `to_string` to print the config.
=> chore(cli): config print without `to_string`

src/git.rs, src/message.rs, src/rule/type_empty.rs
Because some commit like `fuga` is parsed as `None`...
=> fix(cli): fallback to description when no type is found

src/rule/scope.rs, src/rule/type.rs, web/src/content/docs/rules/scope.md, web/src/content/docs/rules/type.md
Resolves: https://github.com/KeisukeYamashita/commitlint-rs/issues/256
Some users want to disable scopes (or types), thus I want to improve the message when the input violates.
=> feat(cli): improve message for disabled scopes and types

src/rule/scope.rs, src/rule/type.rs
Because `len` should not compare to `0` 🙏
=> fix(cli): clippy lint for length comparision

.github/workflows/release.yaml
Because the artifact name must be unique in the workflow.
=> fix(.github): artifact name for artifacts in release

src/rule/description_empty.rs
Fixes: https://github.com/KeisukeYamashita/commitlint-rs/issues/257
Currently, the rule is only checking if the description is `None` or not.
But the empty string `"` must also be checked.
=> fix(cli): empty string check for description

src/git.rs, src/message.rs, src/rule/scope.rs, src/rule/type.rs
Because when the scope or type was `""`, it was not working as expected.
=> fix(cli): unexpected error on `""` (empty) scope or type input

web/src/content/docs/config/configuration.md
This fixes case of 
```console
Failed to load config: Failed to parse configuration file: RULE: unknown variant `warn`, expected one of `error`, `ignore`, `warning
```
=> doc(web): typo fix `warn` -> `warning`

web/src/content/docs/config/default.md
This fixes case of 
```console
Failed to load config: Failed to parse configuration file: rules.scope-max-length.level: unknown variant `warn`, expected one of `error`, `ignore`, `warning
```
=> docs(configuration): typo fix warn to warning

src/rule/description_format.rs, src/rule/scope_format.rs, src/rule/type_format.rs
Because we should avoid using `unwarp` and gracefully handle the errors.
=> chore(cli): error handle format regex error

src/git.rs, src/rule/description_format.rs, src/rule/scope_format.rs, src/rule/type_format.rs
Fixes: https://github.com/KeisukeYamashita/commitlint-rs/issues/290
Commit messages like `'feat(ci): ` and `feat: it should work'` fail.
=> fix(cli): description empty parse panic

Cargo.toml
This is needed since the crate name and archive prefix differ.
Related: #45
=> chore(other): enable cargo binstall

.github/workflows/release.yaml
To maintain 💅 
Note that `v2` requires to use the `v4` of `actions/deploy-pages` GitHub Actions.
=> bump(.github): withastro to `v2`

.github/workflows/lint.yaml
Because a major release was released and I want to keep it up to date.
[v1.0.0, sksat/action-clippy](https://github.com/sksat/action-clippy/releases/tag/v1.0.0)
=> bump(.github): `actions-clippy` to `v1.0.0`

Dockerfile
To keep the project up to date.
=> bump(cli): rust to `1.81`

src/rule/scope_format.rs
Typo... this makes the user confusing because it emits errors like it has problems on description but in reality, it's on the scope.
=> fix(cli): typo `desc` to `scope` in scope related rules

web/src/content/docs/config/default.md, web/src/content/docs/rules/scope-empty.md
As you can see here: 
https://github.com/KeisukeYamashita/commitlint-rs/blob/87ce94983778126ca1faabcaaaa680296f106e3c/src/rule.rs#L200
by default, the rule is ignored.
=> fix(web): default config on default rules page

src/rule/scope.rs, web/src/content/docs/rules/scope.md
Signed-off-by: KeisukeYamashita <19yamashita15@gmail.com># Why
Resolves: https://github.com/KeisukeYamashita/commitlint-rs/issues/355
In some cases,  scope can be optional, but users may want to apply an allow list if a value is provided.
Currently, the `scope-empty` and `scope` are exclusive, and this policy can be configured.
=> feat(cli): add optional field for scope

.github/workflows/release.yaml
Docker images are portable scripts, meaning users don't need to understand the underlying programming language.
Also, the CLI is also `commitlint` (without the `-rs`) so I think it's better to name the image without the `-rs`.
=> fix(.github): docker image name without `-rs`

.github/ISSUE_TEMPLATE/feature_request.md
=> chore(.github): add feature request template

Cargo.lock, Cargo.toml, cli/src/config.rs, web/src/content/docs/config/configuration.md
I don't recall why I chose `-g` but `-c` is more understandable for `--config`.
=> feat(cli): modify config short flag to `-c`

.github/workflows/release.yaml, .gitignore, cli/src/git.rs, web/src/content/docs/config/IDE.md
Follow up for this https://github.com/KeisukeYamashita/commitlint-rs/pull/389
Since a fantastic feature has been added, we should document this to onboard the users/developers.
=> feat(web): add IDE document

.github/workflows/release.yaml
Because now we use Cargo workspaces.
=> fix(.github): specify package name in cargo build

cli/Dockerfile
Since we now use Cargo workspaces, we have to update the Dockerfile too.
=> fix(cli): dockerfile to adapt to workspaces

.github/workflows/ci.yaml
To test whether the schema generation successes.
=> feat(.github): add schema generation test CI

.github/workflows/release.yaml, Cargo.lock, cli/Cargo.toml, schema/Cargo.toml
Since we migrate to Cargo workspace, we have to change the context and the file path to the Dockerfile.
I also accidentally updated the package name so I've reverted it.
=> fix(cli): package name and dockerfile path

.github/workflows/release.yaml
Since I use the `context: .`, I can use the Git context.
Ref: https://github.com/docker/build-push-action/issues/989#issuecomment-1779108258
=> fix(cli): transfer dockerfile using Git context

.github/workflows/release.yaml
Solves: https://github.com/KeisukeYamashita/commitlint-rs/issues/398
As the title says, the release CI is failing.
Now we use Cargo workspace, I'll remove the default directory configuration which used to point to `cli/`.
=> fix(.github): default dir configuration from release workflow

Dockerfile
To maintain this project, follow the latest release of Rust.
=> bump(cli): rust to `1.83`

.github/workflows/release.yaml, Cargo.lock, Cargo.toml
=> fix(.github): runtime comment on build step in release

web/src/content/docs/config/IDE.md, web/src/content/docs/index.mdx
=> fix(web): broken links on webpage

.github/workflows/release.yaml
This runner is already deprecated and it will not spin up the CI.
=> fix(.github): replace deprecated ubuntu runner with latest
